### ISSUE TITLE
Настроить репозиторий

### ISSUE THREAD

**Issue by alira13** [AlexKutsyk/practicum-android-diploma#12]

**Comment by NatalyaManzha** [comment]
а что такое настроить репозиторий?  там есть 2 задачи для обоих - и для поиска, и для настроек. который?

**Comment by alira13** [comment]
Не, гитовый репозиторий. То что Саша настраивать начинал. Чтобы всякие там проверки проходили

**Comment by alira13** [comment]
@AlexKutsyk можешь себя поставить исполнителем, ты вроде начинал делать. И возможно даже закончил)
