### ISSUE TITLE
Экран настройки фильтра. Исправление логики работы

### ISSUE THREAD

**Issue by AlexKutsyk** [AlexKutsyk/practicum-android-diploma#224]

**Comment by alira13** [comment]
https://github.com/AlexKutsyk/practicum-android-diploma/assets/30824853/78151fd4-bd73-4ccc-a567-1640bd3caf89

Закину сюда
Не выполняется требование: Если в приложении нет сохранённых настроек фильтра, то по умолчанию на экране никакие параметры фильтрации не должны быть выбраны. В том числе пустое поле ввода и снята галочка «Не показывать без зарплаты».
