### ISSUE TITLE
Добавить шрифты и основные стили шрифтов

### ISSUE THREAD

**Issue by NatalyaManzha** [AlexKutsyk/practicum-android-diploma#3]
Начертаний там 6 видов. Все яндекс.
Для текста в зависимости от темы:
Bold 32 черн/бел
Medium 22 черн/бел
Medium 16 черн/бел
Regular 16 черн/бел
Regular 16 серый
Regular 12 серый

**Comment by alira13** [comment]
Через FontFamily будем работать?

**Comment by NatalyaManzha** [comment]
папка со шрифтами и да, через этот атрибут. а есть еще варианты?

**Comment by alira13** [comment]
Ну менее красиво, но более гибко это отдельно выставлять шрифт, отдельно стиль и отдельно вес шрифта. Но я за семейства

**Comment by alira13** [comment]
Поставь себя исполнителем в этой задачке
