### ISSUE TITLE
Добавить в проект необходимые зависимости

### ISSUE THREAD

**Issue by NatalyaManzha** [AlexKutsyk/practicum-android-diploma#4]
Room
Coroutines
Navigation
Fragment
Koin
Glide
Retrofit
для тем - androidx.appcompat
для mvvm - androidx.activity

**Comment by alira13** [comment]
Последние версии будем добавлять?

**Comment by NatalyaManzha** [comment]
самые распоследние) только room я бы оставила протестированной версии 2.5.1 и компилятор 2.6.1

**Comment by SAndreyV1683** [comment]
К этой задаче забыли создать пул реквест
